name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        run: |
          echo ${{ secrets.JFROG_TOKEN }} | docker login mycompany.jfrog.io -u ${{ secrets.JFROG_USER }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t mycompany.jfrog.io/myrepo/myapp:$IMAGE_TAG .
          docker push mycompany.jfrog.io/myrepo/myapp:$IMAGE_TAG

      - name: Update image tag in manifest repo
        run: |
          git clone https://github.com/mycompany/k8s-manifests.git
          cd k8s-manifests
          sed -i "s#image: mycompany.jfrog.io/myrepo/myapp:.*#image: mycompany.jfrog.io/myrepo/myapp:${{ github.sha }}#" deploy/deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "ci@github.com"
          git commit -am "Update image tag to ${{ github.sha }}"
          git push

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idcard-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/idcard-deployments.git
    targetRevision: main
    path: k8s/idcard-service
  destination:
    server: https://kubernetes.default.svc
    namespace: idcard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
